### ISSUE TITLE
Dealer Reihenfolge wurde ein Spieler übersprungen

### ISSUE THREAD

**Issue by janKir** [wizard-online/wizard-online#77]

**Comment by janKir** [comment]
### Ursache: 
Die Unterscheidung ob bei Spielbeginn ein Dealer zufällig ernannt werden soll, oder während des Spiels der Dealer einfach der nächste Spieler wird wurde mit einem einfachen falsy check getroffen.
Wenn der letzte Dealer die PlayerID 0 hatte wurde so der nächste Dealer zufällig gewählt und die Reihenfolge gebrochen.

PR #83 behebt diesen Bug

**Comment by fredo** [comment]
nice catch :D
